DESCRIBE PROD_CATEGORIES;
SELECT * FROM PROD_CATEGORIES;

DESCRIBE PRODUCTS;
SELECT * FROM PRODUCTS;

DESCRIBE CLIENTS;
SELECT * FROM CLIENTS;

DESCRIBE ORDERS;
SELECT * FROM ORDERS;

DESCRIBE ORDER_DETAILS;
SELECT * FROM ORDER_DETAILS;