SELECT 
    C.CLIENT_ID,
    C.CLIENT_FIRST_NAME,
    C.CLIENT_LAST_NAME,
    C.CLIENT_UCN,
    O.ORDER_ID,
    O.ORDER_DATE,
    O_DET.PROD_ID,
    P.PROD_DESCR,
    O_DET.PROD_COUNT,
    P.PROD_PRICE,
    O_DET.PROD_COUNT * P.PROD_PRICE AS FINAL_PRICE,
    P.CAT_ID,
    P_CAT.CAT_DESCR
FROM CLIENTS C
JOIN ORDERS O
    ON C.CLIENT_ID = O.CLIENT_ID
JOIN ORDER_DETAILS O_DET
    ON O.ORDER_ID = O_DET.ORDER_ID
JOIN PRODUCTS P
    ON O_DET.PROD_ID = P.PROD_ID
JOIN PROD_CATEGORIES P_CAT
    ON P.CAT_ID = P_CAT.CAT_ID
ORDER BY
    C.CLIENT_ID,
    O.ORDER_DATE;