-- DROP TABLES IF EXIST --
DROP TABLE ORDER_DETAILS;
DROP TABLE ORDERS;
DROP TABLE CLIENTS;
DROP TABLE PRODUCTS;
DROP TABLE PROD_CATEGORIES;
--------------------------


CREATE TABLE PROD_CATEGORIES
(
    CAT_ID NUMBER,
    CAT_DESCR VARCHAR2(30) NOT NULL,
    
    CONSTRAINT PK_PRODCAT_CID PRIMARY KEY (CAT_ID)
);
    
CREATE TABLE PRODUCTS
(
    PROD_ID NUMBER,
    CAT_ID NUMBER NOT NULL,
    PROD_DESCR VARCHAR(30) NOT NULL,
    PROD_PRICE NUMBER(8,2) NOT NULL,
    
    CONSTRAINT PK_PRODS_PID 
        PRIMARY KEY (PROD_ID),
    CONSTRAINT FK_PRODS_CID_PRODCAT_CID 
        FOREIGN KEY (CAT_ID)
        REFERENCES PROD_CATEGORIES(CAT_ID)
);
    
CREATE TABLE CLIENTS
(
    CLIENT_ID NUMBER,
    CLIENT_FIRST_NAME VARCHAR2(20) NOT NULL, 
    CLIENT_LAST_NAME VARCHAR2(20) NOT NULL,
    CLIENT_UCN CHAR(10),
    
    CONSTRAINT PK_CLNTS_CLID 
        PRIMARY KEY (CLIENT_ID)
);

    
CREATE TABLE ORDERS
(
    ORDER_ID NUMBER,
    CLIENT_ID NUMBER NOT NULL,
    ORDER_DATE DATE NOT NULL,
    
    CONSTRAINT PK_ORDRS_OID 
        PRIMARY KEY (ORDER_ID),
    CONSTRAINT FK_ORDRS_OID_CLNTS_CLID
        FOREIGN KEY (CLIENT_ID)
        REFERENCES CLIENTS(CLIENT_ID)
);

CREATE TABLE ORDER_DETAILS
(
    ORDER_ID NUMBER NOT NULL,
    PROD_ID NUMBER NOT NULL,
    PROD_COUNT NUMBER NOT NULL,
    
    CONSTRAINT FK_ORDRDET_OID_ORDRS_OID
        FOREIGN KEY (ORDER_ID)
        REFERENCES ORDERS(ORDER_ID),
    CONSTRAINT FK_ORDRDET_PID_PRODS_PID
        FOREIGN KEY (PROD_ID)
        REFERENCES PRODUCTS(PROD_ID)
);
